### ISSUE TITLE
cannot open Ldraw model

### ISSUE THREAD

**Issue by codebot6000** [stefanmuller/ldraw2houdini#1] opened 2023-06-15 18:27 UTC
Ldraw sop works fine but when i attempt to use the Ldraw Model shelf button i get a python error
```
Traceback (most recent call last):
  File "ldraw_model", line 5, in <module>
  File "D:\apps/houdini/ldraw2houdini/python3.9libs\ldraw.py", line 274, in main
    t_list_master = build_mpd_model(subfiles, main_subfile, geo_node)
UnboundLocalError: local variable 'main_subfile' referenced before assignment
```

**Comment by stefanmuller** [comment] 2023-06-16 00:26
Hello,

Thank you for raising this issue. Would you mind sending me a link to the .mpd file that you are trying to import, then I can investigate!

Cheers

**Comment by codebot6000** [comment] 2023-06-16 02:36
https://omr.ldraw.org/files/165

if i rename any random file from that site to *.LDR the tool will import them fine, other than the DAT file issues from the site. 

really loving the tool though. super fun! :D

**Comment by stefanmuller** [comment] 2023-06-18 07:49
Happy to hear you are enjoying the tool :)

I just released a new version that should fix a whole bunch of issues with different files. Renaming shouldn't be necessary anymore. In fact, renaming mpd files to ldr isn't a good idea, since those two file formats work very differently.

Could you give the new version a try and let me know if everything works for you now?

![alienator](https://github.com/stefanmuller/ldraw2houdini/assets/13545087/5a304396-524f-4cac-b55f-3c8545b3b6cb)

**Comment by stefanmuller** [comment] 2023-06-23 21:19
I assume no reply means the issue is solved :) Therefore closing this!

**Comment by stefanmuller** [comment] 2023-06-23 21:19
I assume no reply means the issue is solved :) Therefore closing this!

**Closed as completed by stefanmuller** 2023-06-23 21:19 UTC
