### ISSUE TITLE
ldraw tool errors out

### ISSUE THREAD

**Issue by bseage** [stefanmuller/ldraw2houdini#2] opened 2023-06-20 05:28 UTC
I have followed all the instructions and I keep getting this error, I've tried reinstalling and it still pops up.

Error running Python menu script in parameter,
    Material Other (/obj/geo1/brickini_ldraw_part1/ldraw_file_parser/material_other):
Traceback (most recent call last):
  File "/obj/geo1/brickini_ldraw_part1/ldraw_file_parser/material_other", line 2, in expression
  File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.435\python37\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'ldraw'

It repeats with a few different materials as well.

**Comment by stefanmuller** [comment] 2023-06-20 07:17
Hello,

ah it looks like you got a python 3.7 build. Can you get a python 3.9 build of H19.5 and see if that fixes it?

Cheers

**Comment by stefanmuller** [comment] 2023-06-23 21:20
I assume no reply means the issue is solved :) Therefore closing this!

**Closed as completed by stefanmuller** 2023-06-23 21:20 UTC
